cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "weaveworks/tap"

brew "ansible"
brew "awscli"
brew "bat"
brew "circleci"
brew "coreutils"
brew "docker-clean"
brew "exa"
brew "fd"
brew "fish"
brew "gh"
brew "ghq"
brew "gibo"
brew "git"
brew "gnu-sed"
brew "go"
brew "gobject-introspection"
brew "golangci-lint"
brew "graphviz"
brew "helm"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "mysql"
brew "nkf"
brew "node"
brew "nodenv"
brew "pango"
brew "peco"
brew "pyenv"
brew "rbenv"
brew "ruby"
brew "terraform_landscape"
brew "tfenv"
brew "tflint"
brew "tfsec"
brew "the_silver_searcher"
brew "tldr"
brew "tree"
brew "wget"
brew "weaveworks/tap/eksctl"
brew "yarn"

cask "alfred"
cask "clipy"
cask "cmd-eikana"
cask "docker"
cask "goland"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "notion"
cask "pycharm-ce"
cask "zoomus"

mas "Bitwarden", id: 1352778147
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
