name: Test

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  test:
    name: shellcheck
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint
        run: |
          for file in (
            etc/scripts/deploy.sh
            etc/scripts/init.sh
            etc/scripts/install.sh
          ); do
            shellcheck "$file"
          done
