name: Test

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  test:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint
        run: make lint
